apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}-secret
data:
  PAPERMERGE__DATABASE__URL: {{ .Values.database_url | b64enc | quote }}
  PAPERMERGE__AUTH__PASSWORD: {{ .Values.auth__password | b64enc | quote }}
  PAPERMERGE__SECURITY__SECRET_KEY: {{ .Values.security__secret_key | b64enc | quote }}
