apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}-secret
data:
  PAPERMERGE__DATABASE__URL: {{ .Values.database_url | b64enc | quote }}
  PAPERMERGE__AUTH__PASSWORD: {{ .Values.database_url | b64enc | quote }}
