apiVersion: v2
name: papermerge
description: Papermerge helm chart for Kubernetes / standalone architecture
type: application
version: 0.4.1
appVersion: "3.3-cloud-b21"

maintainers:
  - name: Eugen Ciur
    email: "eugen@papermerge.com"
