worker:
  replicaCount: 2
  image:
    tag: "3.3-cloud-b3"

app:
  replicaCount: 2
  image:
    tag: "3.3-cloud-b3"
  logging:
    version: 1
    disable_existing_loggers: false

    formatters:
      verbose:
        format: '%(levelname)s:%(pathname)s:%(lineno)d:%(message)s'

    handlers:
      console:
        level: DEBUG
        class: logging.StreamHandler
        formatter: verbose

    root:
      level: DEBUG
      handlers: [console]

    loggers:
      auth_server:
        level: DEBUG
        handlers: [console]
      papermerge.core:
        level: DEBUG
        handlers: [console]
        propagate: no
      papermerge.search:
        level: DEBUG
        handlers: [console]
        propagate: no
        format: verbose
  publicKey:
    -----BEGIN PUBLIC KEY-----
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqyVi/6ph19l4pFcVqW+4C3pF+5fSza8lJ6xZK5WTZr3O2lzwarw+H9lEl2bF0Y40hcd0nFhEBtPckEhLonGe+ncnL1nuWIVQLijkWnbd737GFWA4VRy8zejXTIdJHV/3iK7pgq/TVxR5wPQ1+XJSGcoH1jV0FGbb5gJVxnc+8kFMyPQH9XfNkVIWAHvNHP8VGGwIo8OwXOioylfiV62Soo8IihN5FBl5TRXrdYtIiGexU2P8UpEvq/Yc5nPQFRvW1n+F5YLn4F+I8kHWwGAhJeJc3RmG9OzSi6rhAKFX5puAOyLRkvguL2wsMrA7KLeZMnrZZB5Vkk1gKxY/03VGBQIDAQAB
    -----END PUBLIC KEY-----

global:
  app:
    auth__oidc_client_id: papermerge
    auth__oidc_authorize_url: "https://auth.k8s.trusel.net/realms/demo/protocol/openid-connect/auth"
    auth__oidc_access_token_url: "https://auth.k8s.trusel.net/realms/demo/protocol/openid-connect/token"
    auth__oidc_logout_url: "https://auth.k8s.trusel.net/realms/demo/protocol/openid-connect/logout"
    auth__oidc_redirect_url: "http://localhost:9000/oidc/callback"
    public_key: "/etc/papermerge/public.key"
    home_url: "http://localhost:9000/"
    main__media_root: "/media"
    main__logging_cfg: "/etc/papermerge/logging.yaml"
  ingress:
    enabled: true
    host: paper.k8s.trusel.net
    cert:
      secretName: k8s-trusel-net-production-tls
  storage:
    enabled: true
  redis:
    enabled: false
    url: "redis://redis:6379/0"
  search:
    enabled: false
    url: "solr://solr-solrcloud-0:8983/paper-index"


autoscaling:
  enabled: false

replicaCount: 3

