worker:
  replicaCount: 2
  image:
    tag: "3.3-cloud-b3"

s3worker:
  replicaCount: 1
  image:
    tag: "0.2.1"
  media_root: "/media"
  logging_cfg: "/etc/papermerge/logging.yaml"
  redis:
    enabled: true
    url: "redis://my-redis-master.default:6379/0"
  resources:
    requests:
      cpu: "300m"
      memory: "800Mi"
    limits:
      cpu: "300m"
      memory: "800Mi"

app:
  replicaCount: 2
  image:
    tag: "3.3-cloud-b7"
  publicKey:
    -----BEGIN PUBLIC KEY-----
    place public key here
    -----END PUBLIC KEY-----
  public_key_path: "/etc/papermerge/public.key"
  media_root: "/media"
  logging_cfg: "/etc/papermerge/logging.yaml"
  oidc_client_id: papermerge
  oidc_authorize_url: "https://auth.k8s.trusel.net/realms/demo/protocol/openid-connect/auth"
  oidc_access_token_url: "https://auth.k8s.trusel.net/realms/demo/protocol/openid-connect/token"
  oidc_logout_url: "https://auth.k8s.trusel.net/realms/demo/protocol/openid-connect/logout"
  oidc_redirect_url: "http://localhost:9000/oidc/callback"
  home_url: "http://localhost:9000/"
  uvicorn_workers: 2
  ingress:
    enabled: true
    host: paper.k8s.trusel.net
    cert:
      secretName: k8s-trusel-net-production-tls
  redis:
    enabled: true
    url: "redis://redis:6379/0"
  search:
    enabled: false
    url: "solr://solr-solrcloud-0:8983/paper-index"
  resources:
    requests:
      cpu: "300m"
      memory: "800Mi"
    limits:
      cpu: "300m"
      memory: "800Mi"


global:
  storage:
    enabled: true
    size: 10Gi
  logging:
    version: 1
    disable_existing_loggers: false

    formatters:
      verbose:
        format: '%(levelname)s:%(pathname)s:%(lineno)d:%(message)s'

    handlers:
      console:
        level: DEBUG
        class: logging.StreamHandler
        formatter: verbose

    root:
      level: DEBUG
      handlers: [console]

    loggers:
      auth_server:
        level: DEBUG
        handlers: [console]
      papermerge.core:
        level: DEBUG
        handlers: [console]
        propagate: no
      papermerge.search:
        level: DEBUG
        handlers: [console]
        propagate: no
        format: verbose
