apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "i3worker.fullname" . }}-config
data:
  PAPERMERGE__MAIN__LOGGING_CFG: {{ .Values.logging_cfg | quote }}
  {{- if .Values.redis.enabled }}
  PAPERMERGE__REDIS__URL: {{ .Values.redis.url | quote }}
  {{- end }}
  PAPERMERGE__SEARCH__URL: {{ .Values.search.url | quote }}
  I3_WORKER_ARGS: {{ .Values.celery_worker_args }}
