apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
data:
  PAPERMERGE__AUTH__OIDC_CLIENT_SECRET: {{ .Values.global.app.oidc_client_secret | b64enc | quote }}
  PAPERMERGE__DATABASE__URL: {{ .Values.global.app.database__url | b64enc | quote }}
