apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}-secret
data:
  PAPERMERGE__AUTH__OIDC_CLIENT_SECRET: {{ .Values.oidc_client_secret | b64enc | quote }}
  PAPERMERGE__DATABASE__URL: {{ .Values.database_url | b64enc | quote }}
