apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "path-tmpl-worker.fullname" . }}-config
data:
  PAPERMERGE__MAIN__LOGGING_CFG: {{ .Values.logging_cfg | quote }}
  PAPERMERGE__MAIN__PREFIX: {{ .Values.prefix }}
  {{- if .Values.redis.enabled }}
  PAPERMERGE__REDIS__URL: {{ .Values.redis.url | quote }}
  {{- end }}
  PATH_TMPL_WORKER_ARGS: {{ .Values.celery_worker_args }}
