worker:
  replicaCount: 2
  image:
    tag: "3.3.0build3"

app:
  replicaCount: 2
  image:
    tag: "3.3.0build3"
  logging:
    version: 1
    disable_existing_loggers: false

    formatters:
      verbose:
        format: '%(levelname)s:%(pathname)s:%(lineno)d:%(message)s'

    handlers:
      console:
        level: DEBUG
        class: logging.StreamHandler
        formatter: verbose

    root:
      level: DEBUG
      handlers: [console]

    loggers:
      auth_server:
        level: DEBUG
        handlers: [console]
      papermerge.core:
        level: DEBUG
        handlers: [console]
        propagate: no
      papermerge.search:
        level: DEBUG
        handlers: [console]
        propagate: no
        format: verbose

global:
  app:
    auth__username: "admin"
    auth__email: "admin@example.com"
    main__media_root: "/media"
    main__logging_cfg: "/etc/papermerge/logging.yaml"
  ingress:
    enabled: true
    host: paper.k8s.trusel.net
    cert:
      secretName: k8s-trusel-net-production-tls
  storage:
    enabled: true
  redis:
    enabled: false
    url: "redis://redis:6379/0"
  search:
    enabled: false
    url: "solr://solr-solrcloud-0:8983/paper-index"


autoscaling:
  enabled: false

replicaCount: 3

