apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "west.fullname" . }}-config
data:
  PAPERMERGE__MAIN__LOGGING_CFG: {{ .Values.logging_cfg | quote }}
  {{- if .Values.redis.enabled }}
  PAPERMERGE__REDIS__URL: {{ .Values.redis.url | quote }}
  {{- end }}
  HEALTH_CHECK_PATH: "/probe/"
  PUBLIC_KEY: "/etc/papermerge/public.key"
