apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ocrworker.fullname" . }}-secret
type: Opaque
data:
  AWS_SECRET_ACCESS_KEY: {{ .Values.aws_secret_access_key | b64enc | quote }}
  PAPERMERGE__DATABASE__URL: {{ .Values.database_url | b64enc | quote }}
