apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  PAPERMERGE__AUTH__USERNAME: {{ .Values.global.conf.app.auth__username | quote  }}
  PAPERMERGE__AUTH__EMAIL: {{ .Values.global.conf.app.auth__email | quote }}
  PAPERMERGE__REDIS__URL: {{ .Values.global.conf.redis.url | quote }}
