apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
data:
  PAPERMERGE__SECURITY__SECRET_KEY: {{ .Values.global.security__secret_key | b64enc | quote }}
  PAPERMERGE__AUTH__PASSWORD: {{ .Values.global.auth__password | b64enc | quote }}
  PAPERMERGE__DATABASE__URL: {{ .Values.global.database__url | b64enc | quote }}
