apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
data:
  PAPERMERGE__SECURITY__SECRET_KEY: {{ .Values.global.secrets.app.security__secret_key | b64enc | quote }}
  PAPERMERGE__AUTH__PASSWORD: {{ .Values.global.secrets.app.auth__password | b64enc | quote }}
