{{- if .Values.global.conf.ingress.enabled -}}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "app.fullname" . }}

spec:
  routes:
  - kind: Rule
    match: Host(`{{ .Values.global.conf.ingress.host }}`) && (PathPrefix(`/api/`) || PathPrefix(`/static/`) || PathPrefix(`/auth/`))
    services:
    - name: {{ include "app.fullname" . }}
      port: {{ .Values.service.port }}
{{- end}}
