apiVersion: v1
kind: ConfigMap
metadata:
  name: logging-config
data:
  logging.yaml: |
    version: 1
    disable_existing_loggers: false

    formatters:
      verbose:
        format: '%(levelname)s:%(pathname)s:%(lineno)d:%(message)s'

    handlers:
      console:
        level: DEBUG
        class: logging.StreamHandler
        formatter: verbose

    loggers:
      auth_server:
        level: DEBUG
        handlers: [console]
      papermerge.core:
        level: DEBUG
        handlers: [console]
        propagate: no
