apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
data:
  promtail.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0

    clients:
      - url: http://loki.monitoring:3100/loki/api/v1/push

    scrape_configs:
      - job_name: papermerge
        static_configs:
          - labels:
              job: app
              __path__: /var/log/papermerge/*.log
